const products = [
  {
    id: "1",
    name: "Budget Laptop",
    category: "Laptops",
    price: 29999,
    description: "Good for students and basic work. 4GB RAM, 128GB storage.",
    tags: ["budget", "student", "basic"],
  },
  {
    id: "2",
    name: "Gaming Laptop",
    category: "Laptops",
    price: 89999,
    description: "High performance for gaming. 16GB RAM, RTX 3060, 512GB SSD.",
    tags: ["gaming", "performance", "gpu"],
  },
  {
    id: "3",
    name: "Office Laptop",
    category: "Laptops",
    price: 54999,
    description: "For office work and meetings. 8GB RAM, good battery life.",
    tags: ["office", "work", "battery"],
  },
  {
    id: "4",
    name: "Wireless Mouse",
    category: "Accessories",
    price: 599,
    description: "Simple wireless mouse for daily use.",
    tags: ["mouse", "wireless", "accessory"],
  },
  {
    id: "5",
    name: "Gaming Mouse",
    category: "Accessories",
    price: 2499,
    description: "RGB gaming mouse with extra buttons.",
    tags: ["gaming", "mouse", "rgb"],
  },
  {
    id: "6",
    name: "Mechanical Keyboard",
    category: "Accessories",
    price: 3499,
    description: "Mechanical keyboard for typing and gaming.",
    tags: ["keyboard", "gaming", "mechanical"],
  },
  {
    id: "7",
    name: "USB-C Hub",
    category: "Accessories",
    price: 1299,
    description: "7-in-1 hub with HDMI, USB ports.",
    tags: ["hub", "usb", "adapter"],
  },
  {
    id: "8",
    name: "Portable SSD",
    category: "Storage",
    price: 5999,
    description: "500GB portable SSD for backup and transfer.",
    tags: ["storage", "ssd", "portable"],
  },
  {
    id: "9",
    name: "Ultrabook Pro",
    category: "Laptops",
    price: 74999,
    description: "Slim and light. 16GB RAM, 512GB SSD, long battery.",
    tags: ["ultrabook", "portable", "premium"],
  },
  {
    id: "10",
    name: "Chromebook",
    category: "Laptops",
    price: 22999,
    description: "For browsing and online work. 4GB RAM, 64GB storage.",
    tags: ["budget", "chromebook", "student"],
  },
  {
    id: "11",
    name: "Laptop Stand",
    category: "Accessories",
    price: 899,
    description: "Adjustable aluminium stand for better posture.",
    tags: ["stand", "ergonomic", "accessory"],
  },
  {
    id: "12",
    name: "Webcam HD",
    category: "Accessories",
    price: 3499,
    description: "1080p webcam with built-in mic for meetings.",
    tags: ["webcam", "video", "office"],
  },
  {
    id: "13",
    name: "USB-C Cable Pack",
    category: "Accessories",
    price: 499,
    description: "Set of 3 braided USB-C cables in different lengths.",
    tags: ["cable", "usb", "charging"],
  },
  {
    id: "14",
    name: "External HDD 1TB",
    category: "Storage",
    price: 4299,
    description: "1TB external HDD for backup and extra storage.",
    tags: ["storage", "hdd", "backup"],
  },
  {
    id: "15",
    name: "NVMe SSD 1TB",
    category: "Storage",
    price: 8999,
    description: "Fast 1TB NVMe SSD for laptops and desktops.",
    tags: ["storage", "ssd", "nvme", "performance"],
  },
  {
    id: "16",
    name: "Laptop Bag",
    category: "Accessories",
    price: 1599,
    description: "Water-resistant laptop bag with padded compartment.",
    tags: ["bag", "portable", "accessory"],
  },
  {
    id: "17",
    name: "Cooling Pad",
    category: "Accessories",
    price: 1299,
    description: "Laptop cooling pad with dual fans.",
    tags: ["cooling", "gaming", "accessory"],
  },
  {
    id: "18",
    name: "Memory Card 128GB",
    category: "Storage",
    price: 999,
    description: "128GB microSD card, Class 10, for phones and cameras.",
    tags: ["storage", "memory", "portable"],
  },
];

module.exports = products;
